# Generated by Django 5.0.1 on 2024-01-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_remove_team_members_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='role',
            field=models.CharField(choices=[('team_leader', 'Team Leader'), ('team_member', 'Team Member')], default='team_member', max_length=200),
        ),
    ]
