# Generated by Django 5.0.1 on 2024-01-07 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_members_name_projectdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetails',
            name='image',
        ),
    ]
