# Generated by Django 5.0.1 on 2024-01-07 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_remove_members_name_members_user_team_team_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='team_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_name', to='teams.team'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.projectdetails')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.members')),
            ],
        ),
    ]
